import {
  Institution,
  AuthUser,
  Role,
  Permission,
  Membership,
  RoleAssignment,
  Invitation,
  AuthSession
} from '../types';

export const INSTITUTIONS: Institution[] = [
  {
    id: 'inst-thapar',
    name: 'Thapar Institute of Engineering and Technology',
    code: 'TIET',
    domain: 'thapar.edu',
    status: 'ACTIVE',
    location: 'Bhadson Road, Patiala, Punjab 147004',
    establishedYear: 1956,
  },
  {
    id: 'inst-derabassi',
    name: 'TIET Dera Bassi Campus',
    code: 'TIET-DB',
    domain: 'thapar.edu',
    status: 'ACTIVE',
    location: 'Dera Bassi Campus, Punjab',
    establishedYear: 2013,
  },
];

export const PERMISSIONS: Permission[] = [
  // Timetable
  { id: 'perm-tt-view', code: 'timetable.view', name: 'View Timetables', module: 'TIMETABLE', description: 'Read-only access to published and section timetables' },
  { id: 'perm-tt-create', code: 'timetable.create', name: 'Generate Timetables', module: 'TIMETABLE', description: 'Execute solvers (Constraint / DSATUR) and create drafts' },
  { id: 'perm-tt-edit', code: 'timetable.edit', name: 'Edit Timetables', module: 'TIMETABLE', description: 'Manually move, reschedule or adjust sessions' },
  { id: 'perm-tt-publish', code: 'timetable.publish', name: 'Publish Master Version', module: 'TIMETABLE', description: 'Commit candidate schedule to official production' },
  { id: 'perm-tt-lock', code: 'timetable.lock', name: 'Lock & Pin Sessions', module: 'TIMETABLE', description: 'Freeze slots, rooms, and faculty to prevent solver moves' },

  // Recovery & Self-Healing
  { id: 'perm-rec-view', code: 'recovery.view', name: 'View Recovery Queue', module: 'RECOVERY', description: 'Inspect pending makeups and recovery opportunities' },
  { id: 'perm-rec-schedule', code: 'recovery.schedule', name: 'Schedule Makeups', module: 'RECOVERY', description: 'Approve and confirm recovery opportunities' },
  { id: 'perm-rec-automatch', code: 'recovery.automatch', name: 'Batch Auto-Match', module: 'RECOVERY', description: 'Trigger autonomous batch self-healing across campus' },

  // Approvals & Simulation
  { id: 'perm-appr-manage', code: 'approval.manage', name: 'Manage Approvals', module: 'POLICY', description: 'Authorize changes inside 24-72h freeze windows' },
  { id: 'perm-whatif-sim', code: 'whatif.simulate', name: 'Run What-If Simulation', module: 'POLICY', description: 'Simulate facility closures and faculty absences' },
  { id: 'perm-whatif-apply', code: 'whatif.apply', name: 'Apply Simulation', module: 'POLICY', description: 'Commit simulated schedule variant to master production' },

  // Faculty & Availability
  { id: 'perm-avail-manage', code: 'availability.manage', name: 'Manage Protected Time', module: 'FACULTY', description: 'Designate Research, Lunch, and Department blocks' },
  { id: 'perm-market-claim', code: 'marketplace.claim', name: 'Claim Free Slots', module: 'FACULTY', description: 'Claim tutorials, makeups or project mentoring slots' },
  { id: 'perm-canc-trigger', code: 'cancellation.trigger', name: 'Cancel Own Class', module: 'FACULTY', description: 'Cancel scheduled session and initiate recovery outbox' },

  // Student & CR
  { id: 'perm-poll-vote', code: 'poll.vote', name: 'Vote in Class Polls', module: 'STUDENT', description: 'Participate in student slot availability polls' },
  { id: 'perm-demand-req', code: 'demand.request', name: 'Launch CR Makeup Demand', module: 'STUDENT', description: 'Class Representative petition for syllabus makeups' },

  // Administration & Auth
  { id: 'perm-auth-manage', code: 'auth.manage', name: 'User & Membership Governance', module: 'AUTH', description: 'Manage pre-authorized emails, memberships, and roles' },
  { id: 'perm-audit-view', code: 'audit.view', name: 'View Audit Logs', module: 'AUDIT', description: 'Review immutable institutional change provenance' },
];

export const ROLES: Role[] = [
  {
    id: 'role-superadmin',
    code: 'SUPER_ADMIN',
    name: 'Super Admin',
    description: 'Global system provisioning, multi-tenant college configuration, and compliance oversight',
  },
  {
    id: 'role-admin',
    code: 'COLLEGE_ADMIN',
    name: 'College Admin / Dean',
    description: 'Institution-level authority, academic calendar, regulatory workload limits, and user provisioning',
  },
  {
    id: 'role-coordinator',
    code: 'COORDINATOR',
    name: 'Timetable Coordinator',
    description: 'Master schedule planning, solver orchestration, freeze window approvals, and recovery management',
  },
  {
    id: 'role-hod',
    code: 'HOD',
    name: 'Head of Department',
    description: 'Departmental syllabus progress tracking, faculty load balance, and elective assignments',
  },
  {
    id: 'role-faculty',
    code: 'FACULTY',
    name: 'Faculty Member',
    description: 'Personal routine management, protected free time, voluntary slot marketplace, and cancellation',
  },
  {
    id: 'role-cr',
    code: 'CLASS_REPRESENTATIVE',
    name: 'Class Representative (CR)',
    description: 'Student demand aggregation, makeup petitions, and class-level consensus polling',
  },
  {
    id: 'role-student',
    code: 'STUDENT',
    name: 'Student',
    description: 'Live daily class schedule, cancellation free-time alerts, and polling participation',
  },
];

export const ROLE_PERMISSIONS_MAP: Record<string, string[]> = {
  'role-superadmin': PERMISSIONS.map(p => p.code),
  'role-admin': PERMISSIONS.map(p => p.code),
  'role-coordinator': [
    'timetable.view', 'timetable.create', 'timetable.edit', 'timetable.publish', 'timetable.lock',
    'recovery.view', 'recovery.schedule', 'recovery.automatch',
    'approval.manage', 'whatif.simulate', 'whatif.apply',
    'audit.view'
  ],
  'role-hod': [
    'timetable.view', 'recovery.view', 'approval.manage', 'availability.manage', 'audit.view'
  ],
  'role-faculty': [
    'timetable.view', 'availability.manage', 'marketplace.claim', 'cancellation.trigger', 'recovery.view'
  ],
  'role-cr': [
    'timetable.view', 'poll.vote', 'demand.request'
  ],
  'role-student': [
    'timetable.view', 'poll.vote'
  ],
};

/**
 * auth.users (Central User Table)
 * One person = one account.
 */
export const USERS: AuthUser[] = [
  {
    id: 'usr-murthy',
    email: 'kn.murthy@thapar.edu',
    name: 'Dr. K. N. Murthy',
    status: 'ACTIVE',
    emailVerified: true,
    createdAt: '2026-08-01T09:00:00Z',
    updatedAt: '2026-10-02T08:00:00Z',
    lastLoginAt: '2026-10-02T08:00:00Z',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=200',
    phone: '+91 175 239 3000',
    department: 'Computer Science and Engineering (CSED)',
    officeLocation: 'Academic Block C, Room 402',
    officeHours: 'Mon & Thu 14:00 - 16:00',
    specialization: 'Combinatorial Optimization & Academic Timetabling',
    twoFactorEnabled: true,
    ssoProvider: 'Google Workspace SAML (thapar.edu)',
    ipAddress: '192.168.10.45 (TIET Intranet)',
    notificationPreferences: { email: true, inApp: true, urgentSms: true },
  },
  {
    id: 'usr-sharma',
    email: 'a.sharma@thapar.edu',
    name: 'Prof. Arvind Sharma',
    status: 'ACTIVE',
    emailVerified: true,
    createdAt: '2026-08-01T09:00:00Z',
    updatedAt: '2026-10-02T07:45:00Z',
    lastLoginAt: '2026-10-02T07:45:00Z',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=200',
    phone: '+91 175 239 3124',
    department: 'Computer Science and Engineering (CSED)',
    officeLocation: 'Academic Block B, Room 308',
    officeHours: 'Tue & Fri 11:00 - 13:00',
    specialization: 'Distributed Database Engines, High-Performance Indexing',
    twoFactorEnabled: true,
    ssoProvider: 'Institutional OAuth2 / SAML',
    ipAddress: '192.168.12.82',
    notificationPreferences: { email: true, inApp: true, urgentSms: false },
  },
  {
    id: 'usr-gupta',
    email: 'p.gupta@thapar.edu',
    name: 'Dr. Priya Gupta',
    status: 'ACTIVE',
    emailVerified: true,
    createdAt: '2026-08-01T09:00:00Z',
    updatedAt: '2026-10-01T14:20:00Z',
    lastLoginAt: '2026-10-01T14:20:00Z',
    avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=200',
    phone: '+91 175 239 3200',
    department: 'Computer Science and Engineering (CSED)',
    officeLocation: 'Academic Block B, Room 304',
    officeHours: 'Wed 10:00 - 12:00',
    specialization: 'Operating Systems Kernels, Real-Time Embedded Systems',
    twoFactorEnabled: true,
    ssoProvider: 'Institutional OAuth2 / SAML',
    ipAddress: '192.168.12.89',
    notificationPreferences: { email: true, inApp: true, urgentSms: true },
  },
  {
    id: 'usr-roy',
    email: 's.roy@thapar.edu',
    name: 'Prof. Sunita Roy',
    status: 'ACTIVE',
    emailVerified: true,
    createdAt: '2026-08-01T09:00:00Z',
    updatedAt: '2026-10-01T11:00:00Z',
    lastLoginAt: '2026-10-01T11:00:00Z',
    avatarUrl: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&q=80&w=200',
    phone: '+91 175 239 3300',
    department: 'School of Mathematics',
    officeLocation: 'Basic Sciences Block, Room 101',
    officeHours: 'Mon to Fri 15:00 - 16:30',
    specialization: 'Discrete Structures, Spectral Graph Theory, Cryptography',
    twoFactorEnabled: true,
    ssoProvider: 'Google Workspace SAML',
    ipAddress: '192.168.14.10',
    notificationPreferences: { email: true, inApp: true, urgentSms: true },
  },
  {
    id: 'usr-aarav',
    email: 'aarav.m@thapar.edu',
    name: 'Aarav Mehta (CR COE-1)',
    status: 'ACTIVE',
    emailVerified: true,
    createdAt: '2026-08-10T10:00:00Z',
    updatedAt: '2026-10-02T08:15:00Z',
    lastLoginAt: '2026-10-02T08:15:00Z',
    avatarUrl: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&q=80&w=200',
    phone: '+91 98712 34567',
    department: 'Computer Science and Engineering (CSED)',
    rollNumber: '102303014',
    sectionId: 'sec-cse-a',
    batch: 'Batch COE-A1',
    specialization: 'B.E. Computer Engineering (Sem 5)',
    twoFactorEnabled: false,
    ssoProvider: 'TIET ActiveDirectory / WebKiosk',
    ipAddress: '172.16.20.104 (Hostel J Wi-Fi)',
    notificationPreferences: { email: true, inApp: true, urgentSms: true },
  },
  {
    id: 'usr-rahul',
    email: 'rahul.v@thapar.edu',
    name: 'Rahul Verma',
    status: 'ACTIVE',
    emailVerified: true,
    createdAt: '2026-08-10T10:00:00Z',
    updatedAt: '2026-10-02T08:00:00Z',
    lastLoginAt: '2026-10-02T08:00:00Z',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=200',
    phone: '+91 98109 87654',
    department: 'Computer Science and Engineering (CSED)',
    rollNumber: '102303042',
    sectionId: 'sec-cse-a',
    batch: 'Batch COE-A2',
    specialization: 'B.E. Computer Engineering (Sem 5)',
    twoFactorEnabled: false,
    ssoProvider: 'TIET ActiveDirectory / WebKiosk',
    ipAddress: '172.16.20.119',
    notificationPreferences: { email: true, inApp: true, urgentSms: false },
  },
  {
    id: 'usr-dean',
    email: 'dean@thapar.edu',
    name: 'Dr. Vikram Sengupta',
    status: 'ACTIVE',
    emailVerified: true,
    createdAt: '2026-07-15T09:00:00Z',
    updatedAt: '2026-10-01T09:30:00Z',
    lastLoginAt: '2026-10-01T09:30:00Z',
    avatarUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&q=80&w=200',
    phone: '+91 175 239 3010',
    department: 'Office of the Dean (Academic Affairs)',
    officeLocation: 'Administration Block, Secretariat 201',
    officeHours: 'Mon & Thu 16:00 - 17:30',
    specialization: 'Academic Regulations & Governance',
    twoFactorEnabled: true,
    ssoProvider: 'Executive SAML 2.0 Hardened Key',
    ipAddress: '10.0.1.5 (Admin Enclave)',
    notificationPreferences: { email: true, inApp: true, urgentSms: true },
  },
  {
    id: 'usr-demo-coordinator',
    email: 'coordinator.demo@demo.thapar.local',
    name: 'Prof. Rajesh K. Demo (Coordinator)',
    status: 'ACTIVE',
    emailVerified: true,
    createdAt: '2026-08-01T09:00:00Z',
    updatedAt: '2026-10-02T08:00:00Z',
    lastLoginAt: '2026-10-02T08:00:00Z',
    department: 'Computer Science and Engineering (CSED)',
    officeLocation: 'Academic Block C, Room 402',
    officeHours: 'Mon & Thu 14:00 - 16:00',
    specialization: 'Combinatorial Optimization & Academic Scheduling',
    twoFactorEnabled: false,
    authorizedWorkspaces: ['Coordinator', 'Faculty'],
    isDemoUser: true,
    notificationPreferences: { email: true, inApp: true, urgentSms: false },
  },
  {
    id: 'usr-demo-faculty',
    email: 'faculty.demo@demo.thapar.local',
    name: 'Dr. Neha Agarwal (Faculty)',
    status: 'ACTIVE',
    emailVerified: true,
    createdAt: '2026-08-01T09:00:00Z',
    updatedAt: '2026-10-02T08:00:00Z',
    lastLoginAt: '2026-10-02T08:00:00Z',
    department: 'Computer Science and Engineering (CSED)',
    officeLocation: 'Academic Block B, Room 304',
    officeHours: 'Wed 10:00 - 12:00',
    specialization: 'Distributed Systems & Operating Systems',
    twoFactorEnabled: false,
    authorizedWorkspaces: ['Faculty'],
    isDemoUser: true,
    notificationPreferences: { email: true, inApp: true, urgentSms: false },
  },
  {
    id: 'usr-demo-student',
    email: 'student.demo@demo.thapar.local',
    name: 'Rohan Sharma (Student)',
    status: 'ACTIVE',
    emailVerified: true,
    createdAt: '2026-08-10T10:00:00Z',
    updatedAt: '2026-10-02T08:00:00Z',
    lastLoginAt: '2026-10-02T08:00:00Z',
    department: 'Computer Science and Engineering (CSED)',
    rollNumber: '102303999',
    sectionId: 'sec-cse-a',
    batch: 'Batch COE-A1',
    specialization: 'B.E. Computer Engineering (Sem 5)',
    twoFactorEnabled: false,
    authorizedWorkspaces: ['Student'],
    isDemoUser: true,
    notificationPreferences: { email: true, inApp: true, urgentSms: false },
  },
  {
    id: 'usr-demo-admin',
    email: 'admin.demo@demo.thapar.local',
    name: 'Dr. Vikram Sengupta (Dean/Admin)',
    status: 'ACTIVE',
    emailVerified: true,
    createdAt: '2026-07-15T09:00:00Z',
    updatedAt: '2026-10-01T09:30:00Z',
    lastLoginAt: '2026-10-01T09:30:00Z',
    department: 'Office of the Dean (Academic Affairs)',
    officeLocation: 'Administration Block, Secretariat 201',
    officeHours: 'Mon & Thu 16:00 - 17:30',
    specialization: 'Academic Regulations & Governance',
    twoFactorEnabled: false,
    authorizedWorkspaces: ['Admin', 'Coordinator'],
    isDemoUser: true,
    notificationPreferences: { email: true, inApp: true, urgentSms: false },
  },
  {
    id: 'usr-demo-hod',
    email: 'hod.demo@demo.thapar.local',
    name: 'Dr. Sunita Rao (HOD)',
    status: 'ACTIVE',
    emailVerified: true,
    createdAt: '2026-08-01T09:00:00Z',
    updatedAt: '2026-10-01T11:00:00Z',
    lastLoginAt: '2026-10-01T11:00:00Z',
    department: 'School of Mathematics',
    officeLocation: 'Basic Sciences Block, Room 101',
    officeHours: 'Mon to Fri 15:00 - 16:30',
    specialization: 'Discrete Structures & Applied Algebra',
    twoFactorEnabled: false,
    authorizedWorkspaces: ['Coordinator', 'Faculty'],
    isDemoUser: true,
    notificationPreferences: { email: true, inApp: true, urgentSms: false },
  },
];

export const INITIAL_MEMBERSHIPS: Membership[] = [
  {
    id: 'mem-demo-1',
    userId: 'usr-demo-coordinator',
    institutionId: 'inst-thapar',
    roleId: 'role-coordinator',
    status: 'ACTIVE',
    createdAt: '2026-08-01T09:00:00Z',
    updatedAt: '2026-08-01T09:00:00Z',
    assignedBy: 'system-demo-provisioner',
  },
  {
    id: 'mem-demo-2',
    userId: 'usr-demo-faculty',
    institutionId: 'inst-thapar',
    roleId: 'role-faculty',
    status: 'ACTIVE',
    createdAt: '2026-08-01T09:00:00Z',
    updatedAt: '2026-08-01T09:00:00Z',
    assignedBy: 'system-demo-provisioner',
  },
  {
    id: 'mem-demo-3',
    userId: 'usr-demo-student',
    institutionId: 'inst-thapar',
    roleId: 'role-student',
    status: 'ACTIVE',
    createdAt: '2026-08-10T10:00:00Z',
    updatedAt: '2026-08-10T10:00:00Z',
    assignedBy: 'system-demo-provisioner',
  },
  {
    id: 'mem-demo-4',
    userId: 'usr-demo-admin',
    institutionId: 'inst-thapar',
    roleId: 'role-admin',
    status: 'ACTIVE',
    createdAt: '2026-07-15T09:00:00Z',
    updatedAt: '2026-07-15T09:00:00Z',
    assignedBy: 'system-demo-provisioner',
  },
  {
    id: 'mem-demo-5',
    userId: 'usr-demo-hod',
    institutionId: 'inst-thapar',
    roleId: 'role-hod',
    status: 'ACTIVE',
    createdAt: '2026-08-01T09:00:00Z',
    updatedAt: '2026-08-01T09:00:00Z',
    assignedBy: 'system-demo-provisioner',
  },
  {
    id: 'mem-1',
    userId: 'usr-murthy',
    institutionId: 'inst-thapar',
    roleId: 'role-coordinator',
    status: 'ACTIVE',
    createdAt: '2026-08-01T09:00:00Z',
    updatedAt: '2026-08-01T09:00:00Z',
    assignedBy: 'usr-dean',
  },
  {
    id: 'mem-2',
    userId: 'usr-sharma',
    institutionId: 'inst-thapar',
    roleId: 'role-faculty',
    status: 'ACTIVE',
    createdAt: '2026-08-01T09:00:00Z',
    updatedAt: '2026-08-01T09:00:00Z',
    assignedBy: 'usr-dean',
  },
  {
    id: 'mem-3',
    userId: 'usr-gupta',
    institutionId: 'inst-thapar',
    roleId: 'role-faculty',
    status: 'ACTIVE',
    createdAt: '2026-08-01T09:00:00Z',
    updatedAt: '2026-08-01T09:00:00Z',
    assignedBy: 'usr-dean',
  },
  {
    id: 'mem-4',
    userId: 'usr-roy',
    institutionId: 'inst-thapar',
    roleId: 'role-hod',
    status: 'ACTIVE',
    createdAt: '2026-08-01T09:00:00Z',
    updatedAt: '2026-08-01T09:00:00Z',
    assignedBy: 'usr-dean',
  },
  {
    id: 'mem-5',
    userId: 'usr-aarav',
    institutionId: 'inst-thapar',
    roleId: 'role-cr',
    status: 'ACTIVE',
    createdAt: '2026-08-10T10:00:00Z',
    updatedAt: '2026-08-10T10:00:00Z',
    assignedBy: 'usr-dean',
  },
  {
    id: 'mem-6',
    userId: 'usr-rahul',
    institutionId: 'inst-thapar',
    roleId: 'role-student',
    status: 'ACTIVE',
    createdAt: '2026-08-10T10:00:00Z',
    updatedAt: '2026-08-10T10:00:00Z',
    assignedBy: 'usr-dean',
  },
  {
    id: 'mem-7',
    userId: 'usr-dean',
    institutionId: 'inst-thapar',
    roleId: 'role-admin',
    status: 'ACTIVE',
    createdAt: '2026-07-15T09:00:00Z',
    updatedAt: '2026-07-15T09:00:00Z',
    assignedBy: 'system',
  },
];

export const INITIAL_ROLE_ASSIGNMENTS: RoleAssignment[] = [
  {
    id: 'ra-1',
    institutionId: 'inst-thapar',
    email: 'kn.murthy@thapar.edu',
    roleId: 'role-coordinator',
    status: 'CLAIMED',
    notes: 'Chief Academic Timetable Officer',
    createdAt: '2026-07-20T09:00:00Z',
    updatedAt: '2026-08-01T09:00:00Z',
  },
  {
    id: 'ra-2',
    institutionId: 'inst-thapar',
    email: 'a.sharma@thapar.edu',
    roleId: 'role-faculty',
    status: 'CLAIMED',
    notes: 'Professor, Dept of Computer Science (DBMS)',
    createdAt: '2026-07-20T09:00:00Z',
    updatedAt: '2026-08-01T09:00:00Z',
  },
  {
    id: 'ra-3',
    institutionId: 'inst-thapar',
    email: 'p.gupta@thapar.edu',
    roleId: 'role-faculty',
    status: 'CLAIMED',
    notes: 'Assoc. Professor, Operating Systems',
    createdAt: '2026-07-20T09:00:00Z',
    updatedAt: '2026-08-01T09:00:00Z',
  },
  {
    id: 'ra-4',
    institutionId: 'inst-thapar',
    email: 's.roy@thapar.edu',
    roleId: 'role-hod',
    status: 'CLAIMED',
    notes: 'Head of Department, Mathematics & Basic Sciences',
    createdAt: '2026-07-20T09:00:00Z',
    updatedAt: '2026-08-01T09:00:00Z',
  },
  {
    id: 'ra-5',
    institutionId: 'inst-thapar',
    email: 'dean@thapar.edu',
    roleId: 'role-admin',
    status: 'CLAIMED',
    notes: 'Dean of Academic Affairs',
    createdAt: '2026-07-15T09:00:00Z',
    updatedAt: '2026-07-15T09:00:00Z',
  },
  {
    id: 'ra-6',
    institutionId: 'inst-thapar',
    email: 'faculty@thapar.edu',
    roleId: 'role-faculty',
    status: 'PRE_AUTHORIZED',
    notes: 'Assistant Professor (CSED)',
    createdAt: '2026-09-15T09:00:00Z',
    updatedAt: '2026-09-15T09:00:00Z',
  },
  {
    id: 'ra-7',
    institutionId: 'inst-thapar',
    email: 'hod.ece@thapar.edu',
    roleId: 'role-hod',
    status: 'PRE_AUTHORIZED',
    notes: 'Head of ECED',
    createdAt: '2026-09-20T09:00:00Z',
    updatedAt: '2026-09-20T09:00:00Z',
  },
];

export const INITIAL_SESSIONS: AuthSession[] = [
  {
    id: 'sess-murthy-01',
    userId: 'usr-murthy',
    institutionId: 'inst-thapar',
    roleId: 'role-coordinator',
    token: 'jwt_tok_coord_89a1c3f2',
    createdAt: '2026-10-02T08:00:00Z',
    expiresAt: '2026-10-03T08:00:00Z',
    lastActiveAt: '2026-10-02T08:15:00Z',
    isRevoked: false,
  },
];
